classes:
  - cluster.virtual-mcp11-aio
parameters:
  _param:
    linux_system_codename: xenial
  linux:
    system:
      name: cfg01
      domain: ${_param:cluster_domain}
      purge_repos: ${_param:linux_system_purge_repos}
  salt:
    api:
      pkgs:
       - salt-api
       - python-cherrypy3
    master:
      worker_threads: 5
      environment:
        prd:
          formula:
            # Until patch to reclass-system is merged https://gerrit.mcp.mirantis.net/#/c/20665/
            # and reclass bumped.
            oslo_templates:
              source: pkg
              name: salt-formula-oslo-templates
